name=JoyPi_Advanced_ESP32
version=1.0.0
author=Joy-IT <support@joy-it.de>
maintainer=Joy-IT <support@joy-it.de>
paragraph=sentence=This library is a collection for the ESP32 for two modules on the Joy-Pi Advanced. All other needed libraries are set as dependency. See [here](https://www.joy-pi.net) for more information.
category=Sensors
url=https://github.com/joy-it/JoyPi_Advanced_ESP32
architectures=esp32
includes=ADC_32.h,Gyroscope_32.h, Keypad_MCP.h
depends=Adafruit BusIO,Adafruit LED Backpack Library,Adafruit MPR121,Adafruit NeoPixel,Adafruit SSD1306,Adafruit GFX Library,Adafruit ST7735 and ST7789 Library,IRremote,DHT sensor library,ESP32_Servo,hd44780,Keypad,OneWire,MFRC522,RTCDS1307,VEML6040,MS5xxx